; SmartLayerProxy TypeScript - copy from Java project or customize
; For https: server port 8433, iot.port 8004
; For http: server port 8080, iot.port 8003

server.port=8081
udp.port=8083
tcp.port=8082
